export const STOCK_TYPES = {
  LIST: {
    LOAD_REQUEST: "STOCK_LIST_LOAD_REQUEST",
    LOAD_SUCCESS: "STOCK_LIST_LOAD_SUCCESS",
    LOAD_ERROR: "STOCK_LIST_LOAD_ERROR",
  },
  DETAILS: {
    LOAD_REQUEST: "STOCK_DETAILS_LOAD_REQUEST",
    LOAD_SUCCESS: "STOCK_DETAILS_LOAD_SUCCESS",
    LOAD_ERROR: "STOCK_DETAILS_LOAD_ERROR",
  },
};

export const CHAT_TYPES = {
  CREATE: {
    LOAD_REQUEST: "CHAT_CREATE_LOAD_REQUEST",
    LOAD_SUCCESS: "CHAT_CREATE_LOAD_SUCCESS",
    LOAD_ERROR: "CHAT_CREATE_LOAD_ERROR",
  },
};
